# Generated by Django 5.1.15 on 2026-04-26 04:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('admin_ops', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(help_text='Human-readable order ID e.g. ORD-001', max_length=20, primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('script', 'Only Script'), ('letterPaper', 'Only Letter Paper'), ('letter', 'Only Letter'), ('letterBox', 'Letter + Box'), ('letterBoxGift', 'Letter + Box + Gift')], max_length=20)),
                ('paper_quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('payment_pending', 'Payment Pending'), ('payment_rejected', 'Payment Rejected'), ('awaiting_details', 'Awaiting Customer Details'), ('order_placed', 'Order Placed'), ('assigned_to_writer', 'Assigned to Writer'), ('assignment_rejected', 'Assignment Rejected'), ('accepted_by_writer', 'Accepted by Writer'), ('script_submitted', 'Script Submitted'), ('customer_review', 'Customer Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Script Approved'), ('under_writing', 'Under Writing'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='payment_pending', max_length=25)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=150)),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_contact', models.CharField(blank=True, choices=[('sender', 'Sender'), ('recipient', 'Recipient')], max_length=10, null=True)),
                ('relation', models.CharField(blank=True, max_length=50, null=True)),
                ('message_content', models.TextField(blank=True, null=True)),
                ('special_notes', models.TextField(blank=True, null=True)),
                ('express_script', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('payment_ss', models.CharField(blank=True, help_text='Payment screenshot URL', max_length=500, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('style_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('box_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gift_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('express_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pincode_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('early_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('script_content', models.TextField(blank=True, help_text='Final approved script text', null=True)),
                ('revision_note', models.TextField(blank=True, help_text='Customer feedback for revision', null=True)),
                ('user_answers', models.JSONField(default=list, help_text='Answers to mandatory relationship questions')),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=50, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('est_arrival', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('box', models.ForeignKey(blank=True, limit_choices_to={'category': 'box'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_orders', to='catalog.catalogitem')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='admin_ops.coupon')),
                ('gift', models.ForeignKey(blank=True, limit_choices_to={'category': 'gift'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_orders', to='catalog.catalogitem')),
                ('letter_theme', models.ForeignKey(blank=True, limit_choices_to={'category': 'letter_theme'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_theme_orders', to='catalog.catalogitem')),
                ('paper', models.ForeignKey(blank=True, limit_choices_to={'category': 'paper'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_orders', to='catalog.catalogitem')),
                ('script_package', models.ForeignKey(blank=True, limit_choices_to={'category': 'package'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_orders', to='catalog.catalogitem')),
                ('text_style', models.ForeignKey(blank=True, limit_choices_to={'category': 'style'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_orders', to='catalog.catalogitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='accounts.writer')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('payment_pending', 'Payment Pending'), ('payment_rejected', 'Payment Rejected'), ('awaiting_details', 'Awaiting Customer Details'), ('order_placed', 'Order Placed'), ('assigned_to_writer', 'Assigned to Writer'), ('assignment_rejected', 'Assignment Rejected'), ('accepted_by_writer', 'Accepted by Writer'), ('script_submitted', 'Script Submitted'), ('customer_review', 'Customer Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Script Approved'), ('under_writing', 'Under Writing'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=25)),
                ('new_status', models.CharField(choices=[('payment_pending', 'Payment Pending'), ('payment_rejected', 'Payment Rejected'), ('awaiting_details', 'Awaiting Customer Details'), ('order_placed', 'Order Placed'), ('assigned_to_writer', 'Assigned to Writer'), ('assignment_rejected', 'Assignment Rejected'), ('accepted_by_writer', 'Accepted by Writer'), ('script_submitted', 'Script Submitted'), ('customer_review', 'Customer Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Script Approved'), ('under_writing', 'Under Writing'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=25)),
                ('changed_by_id', models.CharField(blank=True, max_length=36, null=True)),
                ('changed_by_role', models.CharField(default='system', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'db_table': 'order_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to='accounts.admin')),
            ],
            options={
                'db_table': 'refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.IntegerField(default=1, help_text='1=initial, 2=first revision, etc.')),
                ('content', models.TextField()),
                ('writer_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_versions', to='orders.order')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_versions', to='accounts.writer')),
            ],
            options={
                'db_table': 'script_versions',
                'ordering': ['-version_num'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('screenshot_url', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Rejection reason or admin note', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_transactions', to='accounts.admin')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_email'], name='orders_custome_cf1fac_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['writer'], name='orders_writer__dd78ac_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_created_77e2b9_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptversion',
            index=models.Index(fields=['order'], name='script_vers_order_i_81614f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scriptversion',
            unique_together={('order', 'version_num')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_505a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['order'], name='transaction_order_i_c4ecd3_idx'),
        ),
    ]
