# Generated by Django 5.1.15 on 2026-04-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Private admin/writer notes (not visible to customer)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_transaction_id',
            field=models.CharField(blank=True, help_text='Bank/UPI reference ID entered by Admin', max_length=100, null=True),
        ),
    ]
