# Generated by Django 5.1.15 on 2026-05-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_internal_notes_transaction_bank_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_letter_length',
            field=models.CharField(blank=True, help_text='Custom length/height if required by letter type', max_length=50, null=True),
        ),
    ]
