# Generated by Django 5.1.15 on 2026-05-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_custom_letter_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_country_code',
            field=models.CharField(default='+91', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_country_code',
            field=models.CharField(blank=True, default='+91', max_length=10, null=True),
        ),
    ]
