# Generated by Django 5.1.15 on 2026-05-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_customer_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(help_text='Human-readable order ID e.g. ORDER-2000', max_length=20, primary_key=True, serialize=False),
        ),
    ]
