# Generated by Django 5.1.15 on 2026-05-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pricing_unit',
            field=models.CharField(default='page', help_text='Unit used for calculation (page/feet)', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per unit at time of order', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_letter_length',
            field=models.CharField(blank=True, help_text='Custom length/quantity if required', max_length=50, null=True),
        ),
    ]
