# Generated by Django 5.1.15 on 2026-05-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_pricing_unit_order_unit_price_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pricing_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='unit_price_snapshot',
        ),
    ]
