# Generated by Django 5.1.15 on 2026-05-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='delayed_submissions_count',
            field=models.IntegerField(default=0, help_text='Number of times writer submitted a script late.'),
        ),
    ]
