# Generated by Django 5.1.15 on 2026-05-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerassignment',
            name='deadline_notified',
            field=models.BooleanField(default=False, help_text='True if writer was alerted about approaching deadline'),
        ),
        migrations.AddField(
            model_name='writerassignment',
            name='sla_notified',
            field=models.BooleanField(default=False, help_text='True if admin was notified about acceptance delay'),
        ),
        migrations.AddField(
            model_name='writerassignment',
            name='submission_due_at',
            field=models.DateTimeField(blank=True, help_text='Calculated when accepted based on SiteSettings', null=True),
        ),
    ]
