# Generated by Django 5.1.15 on 2026-05-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0002_writerassignment_deadline_notified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writerassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Response'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
