# Generated by Django 5.1.15 on 2026-04-26 04:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_upi_id', models.CharField(max_length=100)),
                ('support_email', models.EmailField(max_length=150)),
                ('support_whatsapp', models.CharField(max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('auto_assign_writers', models.BooleanField(default=True)),
                ('default_delivery_fee', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('responded', 'Responded')], default='new', max_length=15)),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'support_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_val', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Amount')], max_length=15)),
                ('max_uses', models.IntegerField(blank=True, help_text='Null = unlimited', null=True)),
                ('current_uses', models.IntegerField(default=0)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('min_order', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='accounts.admin')),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MandatoryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(help_text='Must match RelationCategory name', max_length=50)),
                ('question_text', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandatory_questions', to='accounts.admin')),
            ],
            options={
                'db_table': 'mandatory_questions',
                'ordering': ['relation_type', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='PincodeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_prefix', models.CharField(help_text='First 3-6 digits of pincode', max_length=10, unique=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('region_name', models.CharField(blank=True, help_text='e.g. Hyderabad, Mumbai', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pincode_rules', to='accounts.admin')),
            ],
            options={
                'db_table': 'pincode_rules',
                'ordering': ['zip_prefix'],
            },
        ),
        migrations.CreateModel(
            name='PricingDayRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_limit', models.IntegerField(help_text='e.g. 28 means within 28 days = extra charge', unique=True)),
                ('extra_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('label', models.CharField(blank=True, help_text='Human readable label', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_day_rules', to='accounts.admin')),
            ],
            options={
                'db_table': 'pricing_day_rules',
                'ordering': ['days_limit'],
            },
        ),
    ]
