# Generated by Django 5.1.15 on 2026-04-27 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mandatoryquestion',
            options={'ordering': ['display_order']},
        ),
        migrations.RemoveField(
            model_name='mandatoryquestion',
            name='relation_type',
        ),
    ]
