# Generated by Django 5.1.15 on 2026-05-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0002_alter_mandatoryquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandatoryquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
