# Generated by Django 5.1.15 on 2026-05-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0003_mandatoryquestion_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='min_delivery_lead_days',
            field=models.IntegerField(default=7),
        ),
    ]
