# Generated by Django 5.1.15 on 2026-05-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0004_sitesettings_min_delivery_lead_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='master_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='site_settings/'),
        ),
    ]
