# Generated by Django 5.1.15 on 2026-05-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0005_sitesettings_master_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='frontend_url',
            field=models.URLField(default='http://localhost:8080', help_text='Base URL for frontend links in emails', max_length=255),
        ),
    ]
