# Generated by Django 5.1.15 on 2026-05-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0006_sitesettings_frontend_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='script_submission_deadline_days',
            field=models.IntegerField(default=3, help_text='Days for writer to submit script after accepting'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='writer_acceptance_sla_hours',
            field=models.IntegerField(default=24, help_text='Hours for writer to accept assignment before admin is alerted'),
        ),
    ]
