# Generated by Django 5.1.15 on 2026-04-26 04:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_categories', to='accounts.admin')),
            ],
            options={
                'verbose_name': 'Relation Category',
                'verbose_name_plural': 'Relation Categories',
                'db_table': 'relation_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('paper', 'Letter Paper'), ('box', 'Gift Box'), ('gift', 'Gift Add-on'), ('style', 'Text Style'), ('package', 'Script Package'), ('letter_theme', 'Letter Theme')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='catalog/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='accounts.admin')),
            ],
            options={
                'verbose_name': 'Catalog Item',
                'verbose_name_plural': 'Catalog Items',
                'db_table': 'catalog_items',
                'ordering': ['category', 'title'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='catalog_ite_categor_89e3b0_idx')],
            },
        ),
    ]
