# Generated by Django 5.1.15 on 2026-05-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_delete_relationcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='compatible_boxes',
            field=models.ManyToManyField(blank=True, help_text='Boxes this item fits into, if fits_all_boxes is False', limit_choices_to={'category': 'box'}, to='catalog.catalogitem'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='fits_all_boxes',
            field=models.BooleanField(default=True, help_text='If true, fits in any box. If false, checks compatible_boxes'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='requires_custom_length',
            field=models.BooleanField(default=False, help_text='If true, UI prompts for custom length/height'),
        ),
    ]
