# Generated by Django 5.1.15 on 2026-05-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalogitem_compatible_boxes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='pricing_unit',
            field=models.CharField(choices=[('page', 'Per Page/Letter'), ('feet', 'Per Feet')], default='page', max_length=10),
        ),
    ]
