# Generated by Django 5.1.15 on 2026-05-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_catalogitem_pricing_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Extra price per unit (e.g. per feet) if applicable', max_digits=10),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base price of the item', max_digits=10),
        ),
    ]
