# Generated by Django 5.1.15 on 2026-05-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_catalogitem_price_per_unit_alter_catalogitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='pricing_unit',
        ),
    ]
