# Generated by Django 5.1.15 on 2026-04-26 04:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('entity_type', models.CharField(help_text='e.g. order_payment, catalog_img', max_length=50)),
                ('entity_id', models.CharField(max_length=36)),
                ('uploaded_by', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'assets',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='assets_entity__b3e67c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='Admin or Writer UUID', max_length=36)),
                ('user_role', models.CharField(choices=[('user', 'Customer'), ('writer', 'Writer'), ('admin', 'Admin')], default='admin', max_length=10)),
                ('action_key', models.CharField(help_text='e.g. PAYMENT_VERIFIED', max_length=50)),
                ('entity_type', models.CharField(help_text='e.g. ORDER, WRITER, PRICING', max_length=30)),
                ('entity_id', models.CharField(max_length=36)),
                ('changes', models.JSONField(blank=True, help_text='Before/After snapshot', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['user_id'], name='audit_logs_user_id_73c422_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.CharField(db_index=True, help_text='ID of the user/writer/admin', max_length=36)),
                ('target_role', models.CharField(choices=[('user', 'Customer'), ('writer', 'Writer'), ('admin', 'Admin')], max_length=10)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('script', 'Script'), ('revision', 'Revision'), ('assignment', 'Assignment'), ('payout', 'Payout'), ('delivery', 'Delivery'), ('system', 'System')], max_length=15)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_id', 'target_role', 'is_read'], name='notificatio_target__b6b162_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecureLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('link_type', models.CharField(choices=[('form_fill', 'Form Fill (Details Questionnaire)'), ('script_review', 'Script Review')], max_length=20)),
                ('order_id', models.CharField(db_index=True, max_length=20)),
                ('target_email', models.EmailField(max_length=150)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'secure_links',
                'indexes': [models.Index(fields=['token'], name='secure_link_token_9602e7_idx'), models.Index(fields=['order_id'], name='secure_link_order_i_098208_idx')],
            },
        ),
    ]
